/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RCC_interface.h"
#include "SysTick_interface.h"
#include "GPIO_interface.h"

int main(void)
{/*     Configure PLL to use HSI and set system clock to 80 MHz
*/

	RCC_SETCLK(HSI, RCC_ON);

//	RCC_PLLconfig(HSI);             // Configure HSI as PLL source
//	Configure_PLLM(8);         // Set PLLM (input divider)
//	ConfigurePLL(168);  /// Set PLLN (multiplier)
//	Configure_PLLP(div_PLLPclk2);// Set PLLP (output divider)


	    RCC_SETSYSCLK(SW_HSI);   //  Switch system clock to PLL

	    SystemCoreClockUpdate();   // Update core clock variable

	    SysTick_Init(ProcessorAHB); // Initialize SysTick with new frequency

	    RCC_AHB1_enable(GPIOAEN);   // Enable GPIOA clock
	/*Configure PA5 as output for the LED*/
pin_configer_t PINA5_LED ={
		.port=PORTA,
		.pinNum=5,
	 	.mode=OUTPUT,
		.speed=LOW,
		.outputtype=PUSH_PULL,
		.pulltype=NOPULL
	};
GPIO_u8pininit(&PINA5_LED);
    /* Loop forever */
	while(1){

		/*high on the pin to turn on user led  */
		GPIO_u8setpinvalue(PORTA,PIN5,PIN_HIGH);

		Delay_ms(1000);             // Delay 1000 ms=1sec

		/* Turn LED off*/
		GPIO_u8setpinvalue(PORTA,PIN5,PIN_LOW);
		/*Delay 1000 ms (1 second)*/
		Delay_ms(1000);

	}}
